### ISSUE TITLE
DEMO: Failed maybe caused by the different version of tensorflow

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/objects#5]
Maybe need to specify the version of tensorflow.

```console
$ ml demo objects 
Loading the required Python modules for the ResNet152 model ...

Loading the pre-trained ResNet v1 152 model with 1000 classes ...
    Model loading time: 5263.78 ms

The ResNet152 model will be used for recognizing the images in
'/home/simon/.mlhub/objects'

Please close each image (Ctrl-w) to proceed through the demonstration.

Recognizing the image
'/home/simon/.mlhub/objects/cache/images/croc.jpg' ...
An error was encountered:

2018-12-19 16:06:07.731538: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-12-19 16:06:07.749679: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2018-12-19 16:06:15.198272: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at mkl_softmax_op.cc:167 : Aborted: Operation received an exception:Status: 3, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_softmax_op.cc:164
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_softmax_op.cc:164
	 [[{{node Softmax}} = _MklSoftmax[T=DT_FLOAT, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](resnet_v1_152/logits/BiasAdd, resnet_v1_152/logits/BiasAdd:2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    output = predict_for(json_lod)
  File "/home/simon/.mlhub/objects/objreg_utils.py", line 149, in process_and_score
    results[key] = scoring_func(batch_image, number_results=_NUMBER_RESULTS)
  File "/home/simon/.mlhub/objects/objreg_utils.py", line 130, in call_model
    pred_proba = predict_for(image_array).squeeze()
  File "/home/simon/.mlhub/objects/objreg_utils.py", line 97, in predict_for
    pred, pred_proba = sess.run([logits, probabilities], feed_dict={input_tensor: image})
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_softmax_op.cc:164
	 [[node Softmax (defined at /home/simon/.mlhub/objects/objreg_utils.py:82)  = _MklSoftmax[T=DT_FLOAT, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](resnet_v1_152/logits/BiasAdd, resnet_v1_152/logits/BiasAdd:2)]]

Caused by op 'Softmax', defined at:
  File "demo.py", line 19, in <module>
    predict_for = get_model_api()
  File "/home/simon/.mlhub/objects/objreg_utils.py", line 139, in get_model_api
    scoring_func = create_scoring_func()
  File "/home/simon/.mlhub/objects/objreg_utils.py", line 123, in create_scoring_func
    predict_for = _get_tf_model(model_path)
  File "/home/simon/.mlhub/objects/objreg_utils.py", line 94, in _get_tf_model
    sess, logits, probabilities, input_tensor = _load_tf_model(checkpoint_file)
  File "/home/simon/.mlhub/objects/objreg_utils.py", line 82, in _load_tf_model
    probabilities = tf.nn.softmax(logits)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1722, in softmax
    return _softmax(logits, gen_nn_ops.softmax, axis, name)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1673, in _softmax
    return compute_op(logits, name=name)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 7138, in softmax
    "Softmax", logits=logits, name=name)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

AbortedError (see above for traceback): Operation received an exception:Status: 3, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_softmax_op.cc:164
	 [[node Softmax (defined at /home/simon/.mlhub/objects/objreg_utils.py:82)  = _MklSoftmax[T=DT_FLOAT, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](resnet_v1_152/logits/BiasAdd, resnet_v1_152/logits/BiasAdd:2)]]
```

**Comment by simonzhaoms** [comment]
Solved in commit 883a90a
